require('soapjs');

// Download the wsdl, and create your functions at runtime
// Using optional http auth. WSDL address and endpoints can be https

var wsdl = "http://www.ratp.fr/wsiv/services/Wsiv?wsdl";

var c = soap.createClient(wsdl, {
});

// Emit when we're done with instantiation from wsdl
c.on( "ready", function(){

    // Call a method from the wsdl, which is created at runtime
    // It will be optionally typed (using the wsdl as the basis)
    var request = c.getVersion({
    })

    request.on("end", function( data ){
        console.log( "JSON formatted data from server:" );
        console.log( data );
        console.log( "Actual xml request body generated by invoking runtime method:" );
        console.log( request.requestBody );
        console.log( request.responseBody );
    });
});